/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.usc.pgroup.floe.thriftgen;


public enum TChannelType implements org.apache.thrift.TEnum {
  ROUND_ROBIN(0),
  REDUCE(1),
  LOAD_BALANCED(2),
  CUSTOM(3);

  private final int value;

  private TChannelType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TChannelType findByValue(int value) { 
    switch (value) {
      case 0:
        return ROUND_ROBIN;
      case 1:
        return REDUCE;
      case 2:
        return LOAD_BALANCED;
      case 3:
        return CUSTOM;
      default:
        return null;
    }
  }
}
