/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.usc.pgroup.floe.thriftgen;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

public class TEdge implements org.apache.thrift.TBase<TEdge, TEdge._Fields>, java.io.Serializable, Cloneable, Comparable<TEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TEdge");

  private static final org.apache.thrift.protocol.TField SRC_PELLET_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("srcPelletId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DEST_PELLET_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("destPelletId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CHANNEL_FIELD_DESC = new org.apache.thrift.protocol.TField("channel", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TEdgeTupleSchemeFactory());
  }

  private String srcPelletId; // required
  private String destPelletId; // required
  private TChannel channel; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SRC_PELLET_ID((short)1, "srcPelletId"),
    DEST_PELLET_ID((short)2, "destPelletId"),
    CHANNEL((short)3, "channel");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SRC_PELLET_ID
          return SRC_PELLET_ID;
        case 2: // DEST_PELLET_ID
          return DEST_PELLET_ID;
        case 3: // CHANNEL
          return CHANNEL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SRC_PELLET_ID, new org.apache.thrift.meta_data.FieldMetaData("srcPelletId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEST_PELLET_ID, new org.apache.thrift.meta_data.FieldMetaData("destPelletId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHANNEL, new org.apache.thrift.meta_data.FieldMetaData("channel", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TChannel.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TEdge.class, metaDataMap);
  }

  public TEdge() {
  }

  public TEdge(
    String srcPelletId,
    String destPelletId,
    TChannel channel)
  {
    this();
    this.srcPelletId = srcPelletId;
    this.destPelletId = destPelletId;
    this.channel = channel;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TEdge(TEdge other) {
    if (other.is_set_srcPelletId()) {
      this.srcPelletId = other.srcPelletId;
    }
    if (other.is_set_destPelletId()) {
      this.destPelletId = other.destPelletId;
    }
    if (other.is_set_channel()) {
      this.channel = new TChannel(other.channel);
    }
  }

  public TEdge deepCopy() {
    return new TEdge(this);
  }

  @Override
  public void clear() {
    this.srcPelletId = null;
    this.destPelletId = null;
    this.channel = null;
  }

  public String get_srcPelletId() {
    return this.srcPelletId;
  }

  public void set_srcPelletId(String srcPelletId) {
    this.srcPelletId = srcPelletId;
  }

  public void unset_srcPelletId() {
    this.srcPelletId = null;
  }

  /** Returns true if field srcPelletId is set (has been assigned a value) and false otherwise */
  public boolean is_set_srcPelletId() {
    return this.srcPelletId != null;
  }

  public void set_srcPelletId_isSet(boolean value) {
    if (!value) {
      this.srcPelletId = null;
    }
  }

  public String get_destPelletId() {
    return this.destPelletId;
  }

  public void set_destPelletId(String destPelletId) {
    this.destPelletId = destPelletId;
  }

  public void unset_destPelletId() {
    this.destPelletId = null;
  }

  /** Returns true if field destPelletId is set (has been assigned a value) and false otherwise */
  public boolean is_set_destPelletId() {
    return this.destPelletId != null;
  }

  public void set_destPelletId_isSet(boolean value) {
    if (!value) {
      this.destPelletId = null;
    }
  }

  public TChannel get_channel() {
    return this.channel;
  }

  public void set_channel(TChannel channel) {
    this.channel = channel;
  }

  public void unset_channel() {
    this.channel = null;
  }

  /** Returns true if field channel is set (has been assigned a value) and false otherwise */
  public boolean is_set_channel() {
    return this.channel != null;
  }

  public void set_channel_isSet(boolean value) {
    if (!value) {
      this.channel = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SRC_PELLET_ID:
      if (value == null) {
        unset_srcPelletId();
      } else {
        set_srcPelletId((String)value);
      }
      break;

    case DEST_PELLET_ID:
      if (value == null) {
        unset_destPelletId();
      } else {
        set_destPelletId((String)value);
      }
      break;

    case CHANNEL:
      if (value == null) {
        unset_channel();
      } else {
        set_channel((TChannel)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SRC_PELLET_ID:
      return get_srcPelletId();

    case DEST_PELLET_ID:
      return get_destPelletId();

    case CHANNEL:
      return get_channel();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SRC_PELLET_ID:
      return is_set_srcPelletId();
    case DEST_PELLET_ID:
      return is_set_destPelletId();
    case CHANNEL:
      return is_set_channel();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TEdge)
      return this.equals((TEdge)that);
    return false;
  }

  public boolean equals(TEdge that) {
    if (that == null)
      return false;

    boolean this_present_srcPelletId = true && this.is_set_srcPelletId();
    boolean that_present_srcPelletId = true && that.is_set_srcPelletId();
    if (this_present_srcPelletId || that_present_srcPelletId) {
      if (!(this_present_srcPelletId && that_present_srcPelletId))
        return false;
      if (!this.srcPelletId.equals(that.srcPelletId))
        return false;
    }

    boolean this_present_destPelletId = true && this.is_set_destPelletId();
    boolean that_present_destPelletId = true && that.is_set_destPelletId();
    if (this_present_destPelletId || that_present_destPelletId) {
      if (!(this_present_destPelletId && that_present_destPelletId))
        return false;
      if (!this.destPelletId.equals(that.destPelletId))
        return false;
    }

    boolean this_present_channel = true && this.is_set_channel();
    boolean that_present_channel = true && that.is_set_channel();
    if (this_present_channel || that_present_channel) {
      if (!(this_present_channel && that_present_channel))
        return false;
      if (!this.channel.equals(that.channel))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_srcPelletId = true && (is_set_srcPelletId());
    builder.append(present_srcPelletId);
    if (present_srcPelletId)
      builder.append(srcPelletId);

    boolean present_destPelletId = true && (is_set_destPelletId());
    builder.append(present_destPelletId);
    if (present_destPelletId)
      builder.append(destPelletId);

    boolean present_channel = true && (is_set_channel());
    builder.append(present_channel);
    if (present_channel)
      builder.append(channel);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(TEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(is_set_srcPelletId()).compareTo(other.is_set_srcPelletId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_srcPelletId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.srcPelletId, other.srcPelletId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(is_set_destPelletId()).compareTo(other.is_set_destPelletId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_destPelletId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destPelletId, other.destPelletId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(is_set_channel()).compareTo(other.is_set_channel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_channel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.channel, other.channel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TEdge(");
    boolean first = true;

    sb.append("srcPelletId:");
    if (this.srcPelletId == null) {
      sb.append("null");
    } else {
      sb.append(this.srcPelletId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("destPelletId:");
    if (this.destPelletId == null) {
      sb.append("null");
    } else {
      sb.append(this.destPelletId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("channel:");
    if (this.channel == null) {
      sb.append("null");
    } else {
      sb.append(this.channel);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!is_set_srcPelletId()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'srcPelletId' is unset! Struct:" + toString());
    }

    if (!is_set_destPelletId()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'destPelletId' is unset! Struct:" + toString());
    }

    if (!is_set_channel()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'channel' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
    if (channel != null) {
      channel.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TEdgeStandardSchemeFactory implements SchemeFactory {
    public TEdgeStandardScheme getScheme() {
      return new TEdgeStandardScheme();
    }
  }

  private static class TEdgeStandardScheme extends StandardScheme<TEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SRC_PELLET_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.srcPelletId = iprot.readString();
              struct.set_srcPelletId_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DEST_PELLET_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destPelletId = iprot.readString();
              struct.set_destPelletId_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CHANNEL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.channel = new TChannel();
              struct.channel.read(iprot);
              struct.set_channel_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.srcPelletId != null) {
        oprot.writeFieldBegin(SRC_PELLET_ID_FIELD_DESC);
        oprot.writeString(struct.srcPelletId);
        oprot.writeFieldEnd();
      }
      if (struct.destPelletId != null) {
        oprot.writeFieldBegin(DEST_PELLET_ID_FIELD_DESC);
        oprot.writeString(struct.destPelletId);
        oprot.writeFieldEnd();
      }
      if (struct.channel != null) {
        oprot.writeFieldBegin(CHANNEL_FIELD_DESC);
        struct.channel.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TEdgeTupleSchemeFactory implements SchemeFactory {
    public TEdgeTupleScheme getScheme() {
      return new TEdgeTupleScheme();
    }
  }

  private static class TEdgeTupleScheme extends TupleScheme<TEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.srcPelletId);
      oprot.writeString(struct.destPelletId);
      struct.channel.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.srcPelletId = iprot.readString();
      struct.set_srcPelletId_isSet(true);
      struct.destPelletId = iprot.readString();
      struct.set_destPelletId_isSet(true);
      struct.channel = new TChannel();
      struct.channel.read(iprot);
      struct.set_channel_isSet(true);
    }
  }

}

